.\" ###### Setup ############################################################
.Dd March 18, 2015
.Dt tracebox 1
.Os tracebox
.\" ###### Name #############################################################
.Sh NAME
.Nm tracebox
.Nd A Middlebox Detection Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm tracebox
.Op OPTIONS
host [Lua arguments list ...]
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm tracebox
is a tool that allows to detect middleboxes on any paths, i.e., between a source
and any destination. Tracebox can be viewed as a tool similar to traceroute as
it uses ICMP replies to identify changes in the packets. The fact that tracebox
is able to detect middleboxes comes from the observation that ICMP messages are
often not as defined in RFC792. Indeed it is quite common to receive a ICMP
Time-to-Live exceeded message with the original datagram instead of 64 bits as
described in the standard. This is caused by operating systems configured to
reply with full ICMP (e.g., Linux, Cisco IOS-XR, etc.) as well as the ICMP
Multi-Part Messages extension that standardize the fact that routers using MPLS
tunnels replies and ICMP message containing the full datagram.
If however it receives an ICMP with only a partial probe in the payload, it will
indicate it by appending a [PARTIAL] flag on the modification list.

.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
Every argument passed after the options in conjunction with \-s or \-l will be passed
to the lua interpreter and available in a global vector of strings named 'argv',
in the order they appeared on the command-line.

The following options may be provided:
.Bl -tag -width indent
.It \-h
Display help and exit.
.It \-n
Do not resolve IP adresses.
.It \-6
Use IPv6 for static probe generated.
.It \-u
Use UDP for static probe generated.
.It \-d port
Use the specified port for static probe generated. Default is 80.
.It \-i device
Specify a network interface to operate with.
.It \-m hops_max
Set the max number of hops (max TTL to be reached). Default is 30.
.It \-p probe
Specify the probe to send.
.It \-l inline_script
Run a script.
.It \-s script
Run a script file.
.It \-v
Print more information.
.It \-w
Show warnings when crafting packets.
.It \-f filename
Specify the name of the pcap file.
.It \-j
Change the output format to JSON.
.It \-t timeout
Timeout to wait for a reply after sending a packet. Accepts decimals, default is 1s.
.El

If Tracebox was compiled with curl support:
.Bl -tag -width indent
.It \-q
Cancel automatic upload of the packet capture file.
.It \-c server_url
Specify a server where capture files of each session will be uploaded.
.El

.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It tracebox -p "IP/TCP/MPCAPABLE/mss(9000)" bahn.de
.It tracebox medu.ir
.El
