language: cpp

cache: apt

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake libtool lua5.2 liblua5.2-dev liblua5.2 liblua5.2-0-dbg libpcap-dev g++ autoconf gdb

install:
- sh bootstrap.sh
- ./configure --enable-tests
- ulimit -c

before_script:
- ulimit -c unlimited -S

script:
- make distcheck
- make check

after_failure:
- cat tests/test-suite.log
- COREFILE=$(find . -maxdepth 5 -name "core*" | head -n 1)
- if [[ -f "$COREFILE" ]]; then sudo  gdb -c "$COREFILE" ./src/tracebox/tracebox -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
